template_path: iamRole.yaml
stack_name: entitlements-lambda-execution-role
parameters:
  AssumingServices: 'lambda.amazonaws.com,edgelambda.amazonaws.com'
  RoleNameSuffix: entitlements-lambda-execution-role