template_path: lambdaTrigger.yaml
stack_name: entitlements-kinesis-lambdaTrigger
parameters:
  EventSourceArn: 'arn:aws:kinesis:us-west-2:961515901445:stream/ecomm-entitlements-to-domains-ingest'
  FunctionName: 'crossaccount-kinesis-lambda'
  BatchSize: '1'
  MaximumBatchingWindowInSeconds: '2'